In [2]:
import pandas as pd

In [3]:
splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/openlifescienceai/medmcqa/" + splits["train"])
df.head()

/home/godo/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
0,e9ad821a-c438-4965-9f77-760819dfa155,Chronic urethral obstruction due to benign pri...,Hyperplasia,Hyperophy,Atrophy,Dyplasia,2,single,Chronic urethral obstruction because of urinar...,Anatomy,Urinary tract
1,e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3,Which vitamin is supplied from only animal sou...,Vitamin C,Vitamin B7,Vitamin B12,Vitamin D,2,single,Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. ...,Biochemistry,Vitamins and Minerals
2,5c38bea6-787a-44a9-b2df-88f4218ab914,All of the following are surgical options for ...,Adjustable gastric banding,Biliopancreatic diversion,Duodenal Switch,Roux en Y Duodenal By pass,3,multi,"Ans. is 'd' i.e., Roux en Y Duodenal Bypass Ba...",Surgery,Surgical Treatment Obesity
3,cdeedb04-fbe9-432c-937c-d53ac24475de,Following endaerectomy on the right common car...,Central aery of the retina,Infraorbital aery,Lacrimal aery,Nasociliary aretry,0,multi,The central aery of the retina is a branch of ...,Ophthalmology,None
4,dc6794a3-b108-47c5-8b1b-3b4931577249,Growth hormone has its effect on growth through?,Directly,IG1-1,Thyroxine,Intranuclear receptors,1,single,"Ans. is 'b' i.e., IGI-1GH has two major functi...",Physiology,None

In [ ]:
treatment = df.loc[df['question'].str.contains('treatment') & df['question'].str.contains('infant|child|patient|man|boy|girl')]
treatment['question'].to_csv('datasets/treatment_questions.csv')

treatment.head()

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
437,07cb00a8-27aa-4917-a9b9-369c38b87aac,Ramachandran is on the surgical ward with non-...,Retroperitoneal Lymph Node Dissection (RPLND),Inguinal orchiectomy,Chemotherapy,Radiotherapy,3,multi,Inguinal orchiectomy with high ligation of the...,Surgery,None
590,65f2ce5a-dd89-45fc-a2cd-5f369acffe77,A 9-year-old boy diagnosed as uncomplicated pu...,His 3-year-old sibling should receive INH prop...,A baseline test of auditory function test is e...,Polyahralgia is a potential adverse effect of ...,"His mother, who takes care of him, does not ne...",0,multi,Prophylaxis with INH is always advisable for f...,Pharmacology,"Mycobacterial Diseases (TB, Leprosy and MAC)"
691,9d193952-cd22-4aab-a77e-c28dbfa697ea,A patient present with lower gastrointestinal ...,Intravenous ceftriaxone,Intravenous metronidazole,Intravenous steroids and sulphasalazine,Hydrocoisone enemas,1,single,This may be caused by haemorrhage from the col...,Medicine,G.I.T
708,5fb4705e-3b44-41da-ad08-25688404bdab,A 70 - year- old man was administered penicill...,chlorphenitramine inj.,Epinephrine inj.,High dose hydrocortisone tablet,nebulised salbutamol,1,single,Ans. is 'b' i.e. epinephrine injection Urticar...,Pharmacology,Penicillin & Cephalosporin
953,a227a262-f152-49e8-a5ea-cde7ea09eb7c,A child has mid-crown fracture in a permanent\...,Formocresol pulpotomy,Root canal therapy,Calcium hydroxide pulpotomy,Apexification,3,single,Apexification is the process of inducing the d...,Dental,None

In [5]:
treatment['subject_name'].unique()

array(['Surgery', 'Pharmacology', 'Medicine', 'Dental', 'Anatomy',
       'Pathology', 'Gynaecology & Obstetrics', 'Pediatrics',
       'Psychiatry', 'Orthopaedics', 'Microbiology', 'ENT', 'Skin',
       'Radiology', 'Anaesthesia', 'Biochemistry', 'Unknown',
       'Social & Preventive Medicine', 'Forensic Medicine',
       'Ophthalmology', 'Physiology'], dtype=object)

In [ ]:
treatment.to_csv("datasets/treatment.csv")