In [1]:
import pandas as pd

In [10]:
splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/openlifescienceai/medmcqa/" + splits["train"])
df.head()

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
0,e9ad821a-c438-4965-9f77-760819dfa155,Chronic urethral obstruction due to benign pri...,Hyperplasia,Hyperophy,Atrophy,Dyplasia,2,single,Chronic urethral obstruction because of urinar...,Anatomy,Urinary tract
1,e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3,Which vitamin is supplied from only animal sou...,Vitamin C,Vitamin B7,Vitamin B12,Vitamin D,2,single,Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. ...,Biochemistry,Vitamins and Minerals
2,5c38bea6-787a-44a9-b2df-88f4218ab914,All of the following are surgical options for ...,Adjustable gastric banding,Biliopancreatic diversion,Duodenal Switch,Roux en Y Duodenal By pass,3,multi,"Ans. is 'd' i.e., Roux en Y Duodenal Bypass Ba...",Surgery,Surgical Treatment Obesity
3,cdeedb04-fbe9-432c-937c-d53ac24475de,Following endaerectomy on the right common car...,Central aery of the retina,Infraorbital aery,Lacrimal aery,Nasociliary aretry,0,multi,The central aery of the retina is a branch of ...,Ophthalmology,None
4,dc6794a3-b108-47c5-8b1b-3b4931577249,Growth hormone has its effect on growth through?,Directly,IG1-1,Thyroxine,Intranuclear receptors,1,single,"Ans. is 'b' i.e., IGI-1GH has two major functi...",Physiology,None

In [15]:
df.groupby('subject_name').sample(20).sort_values('subject_name')[['subject_name', 'question', 'opa', 'opb', 'opc', 'opd']].to_csv('datasets/subject_name_sample.csv', index=False)

In [ ]:
treatment = df.loc[df['question'].str.contains('treatment') & df['question'].str.contains('infant|child|patient|man|boy|girl|male|year')]
treatment['question'].to_csv('datasets/treatment_questions.csv')
# agarrar conjunto de ~200 ver que preguntas son buenas, tambien ver las que dejamos afuera
# podes comparar vs chatgpt cuales no funcionan.
# agarrar subconjuntos por tipo de subject_name
treatment.head()

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
437,07cb00a8-27aa-4917-a9b9-369c38b87aac,Ramachandran is on the surgical ward with non-...,Retroperitoneal Lymph Node Dissection (RPLND),Inguinal orchiectomy,Chemotherapy,Radiotherapy,3,multi,Inguinal orchiectomy with high ligation of the...,Surgery,None
590,65f2ce5a-dd89-45fc-a2cd-5f369acffe77,A 9-year-old boy diagnosed as uncomplicated pu...,His 3-year-old sibling should receive INH prop...,A baseline test of auditory function test is e...,Polyahralgia is a potential adverse effect of ...,"His mother, who takes care of him, does not ne...",0,multi,Prophylaxis with INH is always advisable for f...,Pharmacology,"Mycobacterial Diseases (TB, Leprosy and MAC)"
615,6022af1f-be7a-4b78-8cda-43e0bac536e5,"A 28 year old labourer, 3 yrs back presented w...",VDRL,FTA ABS,TPI,RPR,0,single,This is a case of neurosyphilis. A positive no...,Microbiology,None
691,9d193952-cd22-4aab-a77e-c28dbfa697ea,A patient present with lower gastrointestinal ...,Intravenous ceftriaxone,Intravenous metronidazole,Intravenous steroids and sulphasalazine,Hydrocoisone enemas,1,single,This may be caused by haemorrhage from the col...,Medicine,G.I.T
708,5fb4705e-3b44-41da-ad08-25688404bdab,A 70 - year- old man was administered penicill...,chlorphenitramine inj.,Epinephrine inj.,High dose hydrocortisone tablet,nebulised salbutamol,1,single,Ans. is 'b' i.e. epinephrine injection Urticar...,Pharmacology,Penicillin & Cephalosporin

In [ ]:
treatment['subject_name'].unique()
# procedimiento vs. medicamento vs. otra cosa que se me ocurra
#

array(['Surgery', 'Pharmacology', 'Microbiology', 'Medicine', 'Unknown',
       'Dental', 'Anatomy', 'Pathology', 'Gynaecology & Obstetrics',
       'Pediatrics', 'Psychiatry', 'Orthopaedics', 'ENT', 'Skin',
       'Radiology', 'Anaesthesia', 'Ophthalmology', 'Biochemistry',
       'Social & Preventive Medicine', 'Forensic Medicine', 'Physiology'],
      dtype=object)

In [18]:
treatment.groupby('subject_name').sample(20, replace=True).sort_values('subject_name')[['subject_name', 'question', 'opa', 'opb', 'opc', 'opd']].drop_duplicates().to_csv('datasets/subject_name_sample.csv', index=False)

In [8]:
treatment.loc[treatment['subject_name'] == 'Unknown']

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
849,59165dbb-66fe-4ccd-bd9f-26c60ca3c161,"A female, Lalita, aged 26 yrs accidentally tak...",Lavage with charcoal,Dialysis,Alkaline diuresis,Acetylcysteine,3,multi,"Ans. is 'd' i.e Acetylcysteine ""In cases of mo...",Unknown,None
14162,000ed90b-b9ce-45e1-9ae4-4c63cb009d41,A 9-month-old child presented to the ER with c...,Nebulized racemic epinephrine is an accepted t...,Patients can be safely discharged home after a...,Coicosteroids decrease the edema in the laryng...,Oral steroids are not beneficial in mild croup,3,multi,This is a case of acute laryngotracheobronchit...,Unknown,Integrated QBank
20602,8ffa5607-ce85-44dd-92b8-02547af332a5,A 85-year-old male patient has been suffering ...,Rivastigmine,Donepezil,Memantine,Tacrine,2,multi,The patient is suffering from Alzheimer's dise...,Unknown,Integrated QBank
33141,d5e9afe4-9078-4c59-b804-b01a777ea0cc,A 65-year-old patient presented to the medicin...,Cladribine,Vemurafenib,5-fluorouracil,Deoxycoformycin,2,multi,This is a case of hairy cell leukemia. Bone ma...,Unknown,Integrated QBank
37074,e40760c3-5e21-42e5-a03c-710390abee33,A 58-year-old man with cirrhosis complains of ...,Large volume paracentesis,Hemodialysis,Mesocaval shunt,Liver transplantation,3,single,This patient with well advanced cirrhosis and ...,Unknown,None
43152,05fd397f-6c46-4056-9871-f30f2d4efca0,"A 30-year-old female, known case of PCOD, on t...",East African trypanosomiasis,West African trypanosomiasis,South American trypanosomiasis,Visceral leishmaniasis,1,single,The topical application cream which is useful ...,Unknown,Integrated QBank
51450,da5a4975-1338-4395-a177-b880fcfd103a,A 28 year old male presented with rash on his ...,Cyclophosphamide,IVIg,Cyclosporine,Etanercept,0,multi,This is a case of Steven Johnson syndrome with...,Unknown,Integrated QBank
54360,03fc9796-972f-4ae6-8ebd-f86fcd7fed1f,Which of the following human malignancy is hig...,Hodgkin's lymphoma,Neuroblastoma,Burkitt's lymphoma,Mycosis fungoides,2,single,"Ans. c (Burkitt's lymphoma). (Ref. Bobbin's 8,...",Unknown,None
56394,eeb89a1e-eaa1-4715-b411-1cab52fe130e,A 30-year-old construction worker presented wi...,Enoxaparin,Prednisolone,Warfarin,Smoking cessation,3,multi,1st image shows the gangrene of the digits. 2n...,Unknown,Integrated QBank
70576,6eacf931-2cad-482d-97d9-354bdec07e81,"A 60-year-old male, a known case of COPD with ...",Cephalosporins,Aminoglycosides,Vancomycin,Linezolid,0,multi,This is a case of enterococcus infection which...,Unknown,Integrated QBank
73413,d1144453-44ac-456b-b91f-715f554a2b54,A 55 year old cardiac patient who wason long t...,Digoxin,Verapamil,Amiodarone,Propranolol,2,single,"The image shows “vortex keratopathy”.Here,ther...",Unknown,None
85830,827e7c1d-42b0-4def-ac8c-92fb2b0d6d39,A30-year woman 2+0. hypertension have menorrha...,Combined pills,MIRENA,Hysterectomy,Transcervical resection of endometrium,1,single,Ans-B MIRENA (Ref: Novaks 15/e p788; Williams ...,Unknown,None
97072,cb0ca47d-abc5-4e93-b8bf-52993b7d9218,"A patient who was initially smear positive, wh...",Defaulter,Failure case,Relapse,None of the above,1,multi,Failure case: A patient who was initially smea...,Unknown,None
104048,c10ffd00-9f2a-45d3-8ea2-86e04b1127ec,A woman presents to the Gynecology outpatient ...,Burch Colposuspension,Kelly's Procedure,Sling Suspension Procedure,Tension Free Vaginal Taping,3,single,Ans-D Tension Free Vaginal Taping (Ref. Shaw G...,Unknown,None
106498,a39e53ae-7616-4a17-9414-1bd4acbc7d96,A 40-year-old G3P3 complains of urge hesitancy...,Kegel exercises,Bladder training,Biofeedback,Antidepressants,0,multi,This patient’s presentation is most consistent...,Unknown,None
108591,e5b806c7-b0f5-4101-892a-d9534a25509a,A 35 year old male with history of multiple se...,Cefixime+ azithromycin,Ceftriaxone + quinolone,Erythromycin,Ceftriaxone + doxycycline,0,multi,Ans-A Cefixime+ azithromycin,Unknown,None
110604,696c710f-3003-4259-b1c6-4dc3757078f2,A 6-year-old child with recurrent URTI with mo...,Tonsillectomy,Grommet insertion,Myringotomy with grommet insertion,Adenoidectomy with grommet insertion,3,single,Adenoidectomy with grommet insertionAns. 'd' i...,Unknown,None
114371,db82db2e-f4f3-474e-a608-b26fd1c2a267,A 16-month-old boy is brought in by his parent...,Glucocoicoids have no role in the treatment of...,1st line therapy consists of ceftriaxone or ce...,Duration of therapy to be given is 1-2 weeks.,Fluoroquinolones can be given.,3,multi,This is a case of Hemophilus influenzae causin...,Unknown,Integrated QBank
116874,bc31de9c-66e0-4c0f-8e4e-21bfdb6e8a0a,A 70-year-old male presented with severe confu...,Calcitonin,Furosemide,Normal Saline,Prednisolone,3,multi,The chest x-ray is suggestive of metastatic de...,Unknown,Integrated QBank
117278,045f9534-2b60-4d2a-8eab-679494476682,A 65-year-old man with a long history of diabe...,Escherichia coli,Actinomyces israelii,Clostridium perfringens,Staphylococcus aureus,2,single,X-ray of the left lower extremity shows gas in...,Unknown,Integrated QBank
124947,03862932-7e2c-48cc-96c7-8fd451bc250d,Fully humanized antibody that is used in the t...,Etanercept,Anakinra,Infliximab,Adalimumab,3,single,Ref: Katzung’s ‘Basic and Clinical Pharmacol...,Unknown,None
127367,cd2a2b9f-817e-46e3-9bab-949e9445ea66,A 40-year-old female G4P4L3A1 who gave bih to ...,Lymphocytic myocarditis,Eosinophilic myocarditis,Basophilic myocarditis,Neutrophilic myocarditis,0,single,This is a case of peripaum cardiomyopathy. Gro...,Unknown,Integrated QBank
140311,6f7ab13f-2f64-4cbb-85bb-537f87f5f967,A six-year-old child is admitted to the Paedia...,Uremia,Hyponatremia,Hypocalcemia,Tacrolimus Toxicity,3,single,Ans-D,Unknown,None
140695,efbd0a39-571c-47bc-af90-373748a147e5,A 80-year-old male patient recently diagnosed ...,G1-S transition,S phase,G2-M transition,M phase,3,single,R - CHOP regimen includes Rituximab Cyclophosp...,Unknown,Integrated QBank
148411,5521785a-32e3-4e54-b97d-b23b3faadfd0,"A 30 yrs woman 2+0, hypertension have menorrha...",Combined pills,MIRENA,Hysterectomy,Transcervical resection of endometrium,1,single,"Ans. is 'b' i.e., MIRENA * The question does n...",Unknown,None
164213,3fb8347f-b387-471a-9f09-6f668ab8b23d,An 18 year old girl presents with predominantl...,Topical retinoids,Systemic retinoids,Systemic antibiotics,Topical steroids,0,single,"Ans. is 'a' i.e., Topical retinoids o Topical ...",Unknown,None
165609,17493d13-7530-434e-b3ed-f67229eef955,A 25-year-old male presented with high-grade f...,Oral ciprofloxacin,Packed cell transfusion,Iv ciprofloxacin,Colony stimulating factor,0,multi,Ans (a) ref: harrison 17 page no: 539From his ...,Unknown,None
165851,44f748c7-5f7b-4557-8ec8-481a36f6830e,A 30-year-old male patient came to emergency d...,Acyclovir,Ganciclovir,Famiciclovir,Foscarnet,3,single,The image shows dermatomal distribution of ves...,Unknown,Integrated QBank
177133,41256fd7-a11f-4523-8d4f-e3433d2d11b8,A patient presented with a 1 x 1.5 cms growth ...,Laser ablation,Interstitial brachytherapy,External beam radiotherapy,Chemotherapy,1,single,Ans- B Interstitial brachytherapy Ref- Althoug...,Unknown,None

In [5]:
treatment.to_csv("datasets/treatment.csv")