In [6]:
import pandas as pd
import json

In [7]:
# Load the batch response JSONL file and extract custom_id and response message content
response_answerable = []
with open('../batch/responses_answerable_20250914_142207.jsonl', 'r') as f:
    for line in f:
        data = json.loads(line)
        res = json.loads(data.get('response').replace('```json', '').replace('```', ''))
        response_answerable.append({
            'id': data.get('custom_id'),
            'llm_label': res['answerable'],
            'llm_reason': res['reason']
        })

response_df = pd.DataFrame(response_answerable)
response_df.head()

,id,llm_label,llm_reason
0,81e801d1-39cc-4d64-ab64-10619c171673,False,Question explicitly references options.
1,07cb00a8-27aa-4917-a9b9-369c38b87aac,False,Question explicitly references options with 'e...
2,65f2ce5a-dd89-45fc-a2cd-5f369acffe77,False,The question explicitly references options to ...
3,59165dbb-66fe-4ccd-bd9f-26c60ca3c161,False,Question explicitly references options with 't...
4,9d193952-cd22-4aab-a77e-c28dbfa697ea,False,Question explicitly references options.

In [19]:
treatment_df = pd.read_csv('treatment.csv', index_col=0)

df = pd.merge(treatment_df, response_df, on='id', how='left')
df.to_csv('treatment_with_answerable.csv')
df.head()

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name,llm_label,llm_reason
0,07cb00a8-27aa-4917-a9b9-369c38b87aac,Ramachandran is on the surgical ward with non-...,Retroperitoneal Lymph Node Dissection (RPLND),Inguinal orchiectomy,Chemotherapy,Radiotherapy,3,multi,Inguinal orchiectomy with high ligation of the...,Surgery,NaN,False,Question explicitly references options with 'e...
1,65f2ce5a-dd89-45fc-a2cd-5f369acffe77,A 9-year-old boy diagnosed as uncomplicated pu...,His 3-year-old sibling should receive INH prop...,A baseline test of auditory function test is e...,Polyahralgia is a potential adverse effect of ...,"His mother, who takes care of him, does not ne...",0,multi,Prophylaxis with INH is always advisable for f...,Pharmacology,"Mycobacterial Diseases (TB, Leprosy and MAC)",False,The question explicitly references options to ...
2,6022af1f-be7a-4b78-8cda-43e0bac536e5,"A 28 year old labourer, 3 yrs back presented w...",VDRL,FTA ABS,TPI,RPR,0,single,This is a case of neurosyphilis. A positive no...,Microbiology,NaN,True,The question is focused on identifying a test ...
3,9d193952-cd22-4aab-a77e-c28dbfa697ea,A patient present with lower gastrointestinal ...,Intravenous ceftriaxone,Intravenous metronidazole,Intravenous steroids and sulphasalazine,Hydrocoisone enemas,1,single,This may be caused by haemorrhage from the col...,Medicine,G.I.T,False,Question explicitly references options.
4,5fb4705e-3b44-41da-ad08-25688404bdab,A 70 - year- old man was administered penicill...,chlorphenitramine inj.,Epinephrine inj.,High dose hydrocortisone tablet,nebulised salbutamol,1,single,Ans. is 'b' i.e. epinephrine injection Urticar...,Pharmacology,Penicillin & Cephalosporin,False,The question references a specific treatment o...

In [8]:
response_df['llm_label'].value_counts()

llm_label
False    1041
True      419
Name: count, dtype: int64